spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false

logging.level.uz.uzinfocom.app=INFO
logging.level.org.springframework.security=WARN

app.base-uri=${APP_BASE_URI:https://ykem.sanepid.uz}


# =========================
# SSV SSO - PROD
# =========================
app.auth.providers.sso.enabled=true
app.auth.providers.sso.auth-base-domain=${SSO_AUTH_BASE_DOMAIN:https://sso.ssv.uz}
app.auth.providers.sso.iam-api-base-domain=${SSO_IAM_API_BASE_DOMAIN:https://api2.ssv.uz}

app.auth.providers.sso.issuer-uri=${SSO_ISSUER_URI:${app.auth.providers.sso.auth-base-domain}}
app.auth.providers.sso.signature-mode=PUBLIC_KEY_ENDPOINT
app.auth.providers.sso.public-key-uri=${SSO_PUBLIC_KEY_URI:${app.auth.providers.sso.auth-base-domain}/public-key}

app.auth.providers.sso.validate-audience=false
app.auth.providers.sso.validate-issuer=true
app.auth.providers.sso.missing-issuer-marker-claim=user_info
app.auth.providers.sso.audiences=

app.auth.providers.sso.iam.organization-url-template=${SSO_ORGANIZATION_URL_TEMPLATE:${app.auth.providers.sso.iam-api-base-domain}/v2/Organization/{uuid}}
app.auth.providers.sso.iam.practitioner-url-template=${SSO_PRACTITIONER_URL_TEMPLATE:${app.auth.providers.sso.iam-api-base-domain}/v2/Practitioner/{uuid}}


# =========================
# DHP - PROD
# =========================
app.auth.providers.dhp.enabled=true
app.auth.providers.dhp.auth-base-domain=${DHP_AUTH_BASE_DOMAIN:https://sso.dhp.uz}
app.auth.providers.dhp.fhir-base-domain=${DHP_FHIR_BASE_DOMAIN:https://fhir.dhp.uz}

app.auth.providers.dhp.issuer-uri=${DHP_ISSUER_URI:${app.auth.providers.dhp.auth-base-domain}}
app.auth.providers.dhp.signature-mode=JWKS_URI
app.auth.providers.dhp.jwk-set-uri=${DHP_JWKS_URI:${app.auth.providers.dhp.auth-base-domain}/.well-known/jwks.json}

app.auth.providers.dhp.validate-issuer=true
app.auth.providers.dhp.validate-audience=false
app.auth.providers.dhp.audiences=

app.auth.providers.dhp.iam.organization-url-template=${DHP_ORGANIZATION_URL_TEMPLATE:${app.auth.providers.dhp.fhir-base-domain}/Organization/{uuid}}
app.auth.providers.dhp.iam.practitioner-url-template=${DHP_PRACTITIONER_URL_TEMPLATE:${app.auth.providers.dhp.fhir-base-domain}/Practitioner/{uuid}}