package uz.uzinfocom.app.platform.reference.application.mkb10.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

@Schema(description = """
        Request payload for creating an MKB-10 classifier node. Ids are assigned by the external
        WHO ICD-10 source, not generated by this application, so id is required and must match
        that source's numbering to keep parent/child cross-references valid across re-imports.
        """)
public record Mkb10CreateRequest(
        @Schema(description = "External classifier id, as assigned by the source WHO ICD-10 dataset.",
                example = "1500", requiredMode = Schema.RequiredMode.REQUIRED)
        @NotNull(message = "{reference.mkb10.id.required}")
        @Positive(message = "{reference.mkb10.id.positive}")
        Long id,

        @Schema(description = "Legacy/alternate numeric identifier carried over from a prior classification system.",
                example = "1500")
        Long secondaryId,

        @Schema(description = "Parent node's external id. Null for top-level (chapter) nodes.", example = "12")
        @Positive(message = "{reference.mkb10.parent_id.positive}")
        Long parentId,

        @Schema(description = "Unique ICD-10 code.", example = "A15", requiredMode = Schema.RequiredMode.REQUIRED)
        @NotBlank(message = "{reference.mkb10.code.required}")
        @Size(max = 20, message = "{reference.mkb10.code.max_length}")
        String code,

        @Schema(description = "Depth of this node in the classifier hierarchy, starting from 0.", example = "3")
        @NotNull(message = "{reference.mkb10.level.required}")
        @PositiveOrZero(message = "{reference.mkb10.level.positive_or_zero}")
        Integer level,

        @Schema(description = "Whether this node is a leaf (an assignable diagnosis code) rather than a category heading.",
                example = "true")
        @NotNull(message = "{reference.mkb10.last_level.required}")
        Boolean lastLevel,

        @Schema(description = "Diagnosis name in Uzbek Latin.", example = "Tuberkulyoz")
        @Size(max = 255, message = "{reference.name.max_length}")
        String nameUz,

        @Schema(description = "Diagnosis name in Uzbek Cyrillic.", example = "Туберкулёз")
        @Size(max = 255, message = "{reference.name.max_length}")
        String nameUzCyril,

        @Schema(description = "Diagnosis name in Russian.", example = "Туберкулёз")
        @Size(max = 255, message = "{reference.name.max_length}")
        String nameRu,

        @Schema(description = "Diagnosis name in Karakalpak.", example = "Túberkulez")
        @Size(max = 255, message = "{reference.name.max_length}")
        String nameKaa,

        @Schema(description = "Free-form remark about this classifier node.")
        @Size(max = 2000, message = "{reference.mkb10.comment.max_length}")
        String comment,

        @Schema(description = "How many times this code may be used/selected. Defaults to 1 when omitted.",
                example = "1")
        @Min(value = 0, message = "{reference.mkb10.usage_limit.min}")
        Integer usageLimit
) {
}
