package uz.uzinfocom.app.platform.notification.domain;

public enum NotificationType {
    FORM058_RECEIVED,
    FORM058_ACKNOWLEDGED,
    FORM058_CARD_LINKED,
    FORM058_APPROVED,
    FORM058_CANCELED,
    FORM058_REOPENED,
    FORM0581_RECEIVED,
    FORM0581_ACKNOWLEDGED,
    FORM0581_CARD_LINKED,
    FORM0581_APPROVED,
    FORM0581_CANCELED,
    FORM0581_REOPENED,
    CARD_ASSIGNED,
    ACT_ASSIGNED,
    ACT_LIS_RESPONSE,
    EXPORT_READY
}
